python simulator_performance.py --num 10 --nt 10 --simulator with --append -1
python simulator_performance.py --num 10 --nt 10 --simulator without --append 1
python simulator_performance.py --num 10 --nt 100 --simulator with --append 1
python simulator_performance.py --num 10 --nt 100 --simulator without --append 1
python simulator_performance.py --num 10 --nt 500 --simulator with --append 1
python simulator_performance.py --num 10 --nt 500 --simulator without --append 1
python simulator_performance.py --num 10 --nt 1000 --simulator with --append 1
python simulator_performance.py --num 10 --nt 1000 --simulator without --append 1
python simulator_performance.py --num 10 --nt 2000 --simulator with --append 1
python simulator_performance.py --num 10 --nt 2000 --simulator without --append 1
python simulator_performance.py --num 10 --nt 3000 --simulator with --append 1
python simulator_performance.py --num 10 --nt 3000 --simulator without --append 1
python simulator_performance.py --num 100 --nt 10 --simulator with --append 1
python simulator_performance.py --num 100 --nt 10 --simulator without --append 1
python simulator_performance.py --num 100 --nt 100 --simulator with --append 1
python simulator_performance.py --num 100 --nt 100 --simulator without --append 1
python simulator_performance.py --num 100 --nt 500 --simulator with --append 1
python simulator_performance.py --num 100 --nt 500 --simulator without --append 1
python simulator_performance.py --num 100 --nt 1000 --simulator with --append 1
python simulator_performance.py --num 100 --nt 1000 --simulator without --append 1
python simulator_performance.py --num 100 --nt 2000 --simulator with --append 1
python simulator_performance.py --num 100 --nt 2000 --simulator without --append 1
python simulator_performance.py --num 100 --nt 3000 --simulator with --append 1
python simulator_performance.py --num 100 --nt 3000 --simulator without --append 1
python simulator_performance.py --num 500 --nt 10 --simulator with --append 1
python simulator_performance.py --num 500 --nt 10 --simulator without --append 1
python simulator_performance.py --num 500 --nt 100 --simulator with --append 1
python simulator_performance.py --num 500 --nt 100 --simulator without --append 1
python simulator_performance.py --num 500 --nt 500 --simulator with --append 1
python simulator_performance.py --num 500 --nt 500 --simulator without --append 1
python simulator_performance.py --num 500 --nt 1000 --simulator with --append 1
python simulator_performance.py --num 500 --nt 1000 --simulator without --append 1
python simulator_performance.py --num 500 --nt 2000 --simulator with --append 1
python simulator_performance.py --num 500 --nt 2000 --simulator without --append 1
python simulator_performance.py --num 500 --nt 3000 --simulator with --append 1
python simulator_performance.py --num 500 --nt 3000 --simulator without --append 1
python simulator_performance.py --num 1000 --nt 10 --simulator with --append 1
python simulator_performance.py --num 1000 --nt 10 --simulator without --append 1
python simulator_performance.py --num 1000 --nt 100 --simulator with --append 1
python simulator_performance.py --num 1000 --nt 100 --simulator without --append 1
python simulator_performance.py --num 1000 --nt 500 --simulator with --append 1
python simulator_performance.py --num 1000 --nt 500 --simulator without --append 1
python simulator_performance.py --num 1000 --nt 1000 --simulator with --append 1
python simulator_performance.py --num 1000 --nt 1000 --simulator without --append 1
python simulator_performance.py --num 1000 --nt 2000 --simulator with --append 1
python simulator_performance.py --num 1000 --nt 2000 --simulator without --append 1
python simulator_performance.py --num 1000 --nt 3000 --simulator with --append 1
python simulator_performance.py --num 1000 --nt 3000 --simulator without --append 1
python simulator_performance.py --num 2000 --nt 10 --simulator with --append 1
python simulator_performance.py --num 2000 --nt 10 --simulator without --append 1
python simulator_performance.py --num 2000 --nt 100 --simulator with --append 1
python simulator_performance.py --num 2000 --nt 100 --simulator without --append 1
python simulator_performance.py --num 2000 --nt 500 --simulator with --append 1
python simulator_performance.py --num 2000 --nt 500 --simulator without --append 1
python simulator_performance.py --num 2000 --nt 1000 --simulator with --append 1
python simulator_performance.py --num 2000 --nt 1000 --simulator without --append 1
python simulator_performance.py --num 2000 --nt 2000 --simulator with --append 1
python simulator_performance.py --num 2000 --nt 2000 --simulator without --append 1
python simulator_performance.py --num 2000 --nt 3000 --simulator with --append 1
python simulator_performance.py --num 2000 --nt 3000 --simulator without --append 1
python simulator_performance.py --num 5000 --nt 10 --simulator with --append 1
python simulator_performance.py --num 5000 --nt 10 --simulator without --append 1
python simulator_performance.py --num 5000 --nt 100 --simulator with --append 1
python simulator_performance.py --num 5000 --nt 100 --simulator without --append 1
python simulator_performance.py --num 5000 --nt 500 --simulator with --append 1
python simulator_performance.py --num 5000 --nt 500 --simulator without --append 1
python simulator_performance.py --num 5000 --nt 1000 --simulator with --append 1
python simulator_performance.py --num 5000 --nt 1000 --simulator without --append 1
python simulator_performance.py --num 5000 --nt 2000 --simulator with --append 1
python simulator_performance.py --num 5000 --nt 2000 --simulator without --append 1
python simulator_performance.py --num 5000 --nt 3000 --simulator with --append 1
python simulator_performance.py --num 5000 --nt 3000 --simulator without --append 1
python simulator_performance.py --num 10000 --nt 10 --simulator with --append 1
python simulator_performance.py --num 10000 --nt 10 --simulator without --append 1
python simulator_performance.py --num 10000 --nt 100 --simulator with --append 1
python simulator_performance.py --num 10000 --nt 100 --simulator without --append 1
python simulator_performance.py --num 10000 --nt 500 --simulator with --append 1
python simulator_performance.py --num 10000 --nt 500 --simulator without --append 1
python simulator_performance.py --num 10000 --nt 1000 --simulator with --append 1
python simulator_performance.py --num 10000 --nt 1000 --simulator without --append 1
python simulator_performance.py --num 10000 --nt 2000 --simulator with --append 1
python simulator_performance.py --num 10000 --nt 2000 --simulator without --append 1
python simulator_performance.py --num 10000 --nt 3000 --simulator with --append 1
python simulator_performance.py --num 10000 --nt 3000 --simulator without --append 1